version: '3.8'

services:
  django:
    container_name: django
    build:
      context: ./back
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./back/app:/app
    ports:
      - "8000:8000"
    networks:
      - news_network

  scraper:
    container_name: scraper
    build:
      context: ./scraper
      dockerfile: Dockerfile
    volumes:
      - ./scraper:/app
    networks:
      - news_network

networks:
  news_network:
    driver: bridge
    