# Generated by Django 4.2.11 on 2024-08-26 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=225, unique=True)),
                ('model', models.CharField(choices=[('0', 'JornalGrandeBahia'), ('1', 'LfNews'), ('2', 'VilasMagazine'), ('3', 'BurburinhoNews'), ('4', 'BahiaNoAr'), ('5', 'RelataBahia')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=225, unique=True)),
                ('model', models.CharField(choices=[('0', 'JornalGrandeBahia'), ('1', 'LfNews'), ('2', 'VilasMagazine'), ('3', 'BurburinhoNews'), ('4', 'BahiaNoAr'), ('5', 'RelataBahia')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('model', models.CharField(choices=[('0', 'JornalGrandeBahia'), ('1', 'LfNews'), ('2', 'VilasMagazine'), ('3', 'BurburinhoNews'), ('4', 'BahiaNoAr'), ('5', 'RelataBahia')], default='', max_length=25)),
                ('categories', models.ManyToManyField(related_name='posts', to='post.category')),
                ('tags', models.ManyToManyField(related_name='posts', to='post.tag')),
            ],
        ),
    ]
